### ISSUE TITLE
Crash - logical_volume.rs:164:92 - called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by playlogo** [kalaksi/lightkeeper#15]
Hey, so after around 5 sec of loading the programm crashes with this error: 
```shell
[2024-07-05T19:54:47Z INFO  lightkeeper::module::connection::ssh] Connected to (hidden)
[2024-07-05T19:54:47Z WARN  default] qrc:/qml/DetailsView/HostDetailsMainView.qml:256:25: QML PropertyTable: the delegate's implicitWidth needs to be greater than zero
[2024-07-05T19:54:48Z WARN  lightkeeper::connection_manager] [Vps][package] Command returned non-zero exit code: 1
thread '<unnamed>' panicked at ../src/module/monitoring/storage/lvm/logical_volume.rs:164:92:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x55a5a7657f15 - <unknown>
   1:     0x55a5a7685f5b - <unknown>
   2:     0x55a5a765473f - <unknown>
   3:     0x55a5a7657cee - <unknown>
   4:     0x55a5a76591d9 - <unknown>
   5:     0x55a5a7658f1d - <unknown>
   6:     0x55a5a7659673 - <unknown>
   7:     0x55a5a765951b - <unknown>
   8:     0x55a5a76583d9 - <unknown>
   9:     0x55a5a7659287 - <unknown>
  10:     0x55a5a71c7b13 - <unknown>
  11:     0x55a5a71c7bbc - <unknown>
  12:     0x55a5a71c7ab9 - <unknown>
  13:     0x55a5a72639e8 - <unknown>
  14:     0x55a5a731899f - <unknown>
  15:     0x55a5a7324187 - <unknown>
  16:     0x55a5a765f40b - <unknown>
  17:     0x7fab8fca1e39 - <unknown>
  18:     0x7fab8fd299c4 - __clone
  19:                0x0 - <unknown>
thread '<unnamed>' panicked at ../src/connection_manager.rs:262:60:
called `Result::unwrap()` on an `Err` value: SendError { .. }
stack backtrace:
   0:     0x55a5a7657f15 - <unknown>
   1:     0x55a5a7685f5b - <unknown>
   2:     0x55a5a765473f - <unknown>
   3:     0x55a5a7657cee - <unknown>
   4:     0x55a5a76591d9 - <unknown>
   5:     0x55a5a7658f1d - <unknown>
   6:     0x55a5a7659673 - <unknown>
   7:     0x55a5a7659554 - <unknown>
   8:     0x55a5a76583d9 - <unknown>
   9:     0x55a5a7659287 - <unknown>
  10:     0x55a5a71c7b13 - <unknown>
  11:     0x55a5a71c7fc6 - <unknown>
  12:     0x55a5a72e0bff - <unknown>
  13:     0x55a5a71b6e26 - <unknown>
  14:     0x55a5a7393582 - <unknown>
  15:     0x55a5a739588a - <unknown>
  16:     0x55a5a73965e2 - <unknown>
  17:     0x55a5a765f40b - <unknown>
  18:     0x7fab8fca1e39 - <unknown>
  19:     0x7fab8fd299c4 - __clone
  20:                0x0 - <unknown>
Rayon: detected unexpected panic; aborting
```

**Comment by kalaksi** [comment]
Thanks for reporting. I don't yet understand why I haven't hit this issue myself, but the fix is straightforward so I just implemented it and will do a release soon.

**Comment by kalaksi** [comment]
Let me know if the new version solves the problem

**Comment by playlogo** [comment]
Thank you for this super fast fix! Yes, this solves the problem.
